AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lamby Product Site

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Resources:

  LambyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: ruby2.7
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          RAILS_ENV: !Ref RailsEnv
          RUBYOPT: -W0
      FunctionName: !Sub lamby-${RailsEnv}
      FunctionUrlConfig:
        AuthType: NONE
      Tags:
        env: !Ref RailsEnv
        group: shared
        application: lamby

Outputs:

  LambyLambdaResourceArn:
    Description: Lamby Lambda ARN
    Value: !GetAtt LambyLambda.Arn
